import { Link, useNavigate } from '@tanstack/react-router';
import {
  CalendarClockIcon,
  type LucideIcon,
  MailIcon,
  PhoneIcon,
  ShieldIcon,
  UserIcon,
} from 'lucide-react';
import type React from 'react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { cn } from '@/lib/utils';
import { useUserDeleteDialog } from '@/sample/users/components/user-delete-dialog';
import { UserNotFound } from '@/sample/users/components/user-not-found';
import { userRoles, userStatusStyles } from '@/sample/users/data/user-types';
import { selectUserById, useUsersStore } from '@/sample/users/store/users-store';
import type { User } from '@/sample/users/types/user';

interface UserDetailPageProps {
  userId: string;
}

interface DetailItemProps {
  icon: LucideIcon;
  label: string;
  value: React.ReactNode;
}

function formatDate(value: Date): string {
  return new Intl.DateTimeFormat('en', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(value);
}

function DetailItem({ icon: Icon, label, value }: DetailItemProps) {
  return (
    <div className="flex gap-3 rounded-lg border bg-background p-3">
      <Icon className="mt-0.5 size-4 shrink-0 text-muted-foreground" aria-hidden />
      <div className="min-w-0 space-y-1">
        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p>
        <div className="break-words text-sm font-medium">{value}</div>
      </div>
    </div>
  );
}

function getRoleLabel(user: User): string {
  return userRoles.find((role) => role.value === user.role)?.label ?? user.role;
}

export function UserDetailPage({ userId }: UserDetailPageProps) {
  const navigate = useNavigate();
  const user = useUsersStore(selectUserById(userId));
  const openDeleteDialog = useUserDeleteDialog();

  if (!user) {
    return <UserNotFound userId={userId} />;
  }

  const fullName = `${user.firstName} ${user.lastName}`;

  return (
    <div className="flex flex-1 flex-col gap-6 p-6 md:p-8">
      <header className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <div className="space-y-2">
          <div className="flex flex-wrap items-center gap-2">
            <h1 className="text-2xl font-bold tracking-tight md:text-3xl">{fullName}</h1>
            <Badge variant="outline" className={cn('capitalize', userStatusStyles[user.status])}>
              {user.status}
            </Badge>
          </div>
          <p className="text-sm text-muted-foreground">@{user.username}</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button nativeButton={false} variant="outline" render={<Link to="/sample/users" />}>
            Back
          </Button>
          <Button
            nativeButton={false}
            variant="outline"
            render={<Link to="/sample/users/$userId/edit" params={{ userId: user.id }} />}
          >
            Edit
          </Button>
          <Button
            variant="destructive"
            onClick={() =>
              openDeleteDialog(user, {
                onDeleted: () => void navigate({ to: '/sample/users' }),
              })
            }
          >
            Delete
          </Button>
        </div>
      </header>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
        <Card>
          <CardHeader>
            <CardTitle>Contact profile</CardTitle>
            <CardDescription>Read-only detail view for this sample user.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-3 md:grid-cols-2">
            <DetailItem icon={UserIcon} label="Name" value={fullName} />
            <DetailItem icon={ShieldIcon} label="Role" value={getRoleLabel(user)} />
            <DetailItem icon={MailIcon} label="Email" value={user.email} />
            <DetailItem icon={PhoneIcon} label="Phone" value={user.phoneNumber} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Account timeline</CardTitle>
            <CardDescription>Generated by deterministic faker seed data.</CardDescription>
            <CardAction>
              <Badge variant="secondary">Mock</Badge>
            </CardAction>
          </CardHeader>
          <CardContent className="space-y-3">
            <DetailItem
              icon={CalendarClockIcon}
              label="Created"
              value={formatDate(user.createdAt)}
            />
            <DetailItem
              icon={CalendarClockIcon}
              label="Updated"
              value={formatDate(user.updatedAt)}
            />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
